snozbot/fungus

Assets/Fungus/Flowchart/Scripts/Flowchart.cs
Added a hidden serialized `version` field, an `UpdateVersion()` function, and an overridable `Initialize()` function to the Flowchart component that allow for custom upgrades from previous versions as well as a one-time initialization after each flowchart instance creation.
Updated the default initialization function to reset the event handler of the default block on the newly created flowchart if previous flowcharts are found in `cachedFlowcharts` and the default block uses the default block name (to avoid resetting older previously existing flowcharts).
=> Resets Default Block Event for Additional Flowcharts

Assets/Fungus/Flowchart/Editor/FlowchartEditor.cs, Assets/Fungus/Flowchart/Scripts/Flowchart.cs
Any command or category name that matches an item in the list will not
appear in the add command menu.
=> Added a Hide Commands property to Flowchart

Assets/Fungus/Narrative/Editor/CharacterEditor.cs, Assets/Fungus/Narrative/Scripts/Character.cs, Assets/Fungus/Narrative/Scripts/Commands/Say.cs
The idea of this feature is simple - allow setting default say dialog for Character. It's useful when you have a long dialog with multiple characters with dedicated say dialogs - it's more comfortable to set only character for each say command and not set say dialog for each one explicite in the command.
=> Set say dialog for character

Assets/Fungus/FungusScript/Scripts/FungusScript.cs, Assets/Fungus/FungusScript/Scripts/PODTypeFactory.cs, Assets/Fungus/FungusScript/Scripts/PODTypeFactory.cs.meta, Assets/Tests/FungusScript/FungusTests.unity
MoonSharp’s __new function appears to be unreliable for POD types like
Color, Vector2, etc. This class provides simple factory methods for
constructing these types, which are then exposed through unity.factory
in Lua.
=> Type factory class for constructing POD types like Color

Assets/Fungus/Flowchart/Scripts/Block.cs, Assets/Fungus/Narrative/Scripts/MenuDialog.cs, Assets/Tests/FungusScript/FungusTests.unity
Lua scripts should use the coroutine Execute method directly.
=> Rename non-coroutine Execute to StartExecute to be more descriptive

Assets/Fungus/Flowchart/Editor/BlockEditor.cs
Quick bugfix: If there is another block executing, and then you use the "play selected" command on a non-executing block, both blocks will execute at the same time. I changed it so that it will stop all executing blocks before executing the selected block.
=> Stop all executing blocks on play selected

Assets/Fungus/Audio/Scripts/Commands/PlaySound.cs
Changed to 'No sound clip selected', could make both more universal and say no audio clip selected.
=> No Music clip selected error

Assets/Fungus/Narrative/Resources/MenuDialog.prefab, Assets/Fungus/Narrative/Scripts/MenuDialog.cs, Assets/Fungus/UI/Scripts/SelectOnEnable.cs, Assets/Fungus/UI/Scripts/SelectOnEnable.cs.meta
MenuDialog now has a new bool option: `autoSelectFirstButton`. If enabled, the first interactable button added will be selected automatically. This allows for the menu to be navigated without the need of a mouse, with the Vertical or Horizontal axes as defined by the current Standalone Input Module.
Even if this option is disabled, the menu may be navigated without the need of a mouse thanks to a new GameObject added to the MenuDialog prefab: DefaultSelectable. It's just an invisible Selectable that automatically selects itself when enabled. From there, the user can navigate to the first option with the Vertical input axis. The DefaultSelectable is marked as not interactable, so the user cannot navigate back to it.
=> Allow for menu options to be picked without clicking.

Assets/Fungus/Narrative/Scripts/Character.cs
In the portrait lookup, if you have a blank portrait field on a character, it blows up. This prevents it by checking if there is a portrait to compare against first.
=> Bugfix for when portrait field is blank

Assets/Fungus/Thirdparty/FungusLua/Resources/Lua/fungus.txt, Assets/Fungus/Thirdparty/FungusLua/Scripts/LuaUtils.cs
There was a disconnect between Lua's setsaydialog and c#'s SayDialog.activeSayDialog. I did the simplest thing and made a sync function in luaUtils. Maybe not the fanciest solution but it works.
=> Sync active say dialog when Lua sets the say dialog

Assets/Fungus/Narrative/Scripts/ConversationManager.cs
I found that if I had a bunch of commented out lines, the game would hang and eat up a ton of cpu and memory. This fixes that.
=> Bail out first thing if comment

Assets/Fungus/Narrative/Scripts/ConversationManager.cs
This removes the comment lines during the parsing stage. It also fixes the case that a hide function has no text but displays it anyways.
=> Fix portrait hide bug in Conversation Function

Assets/Fungus/Narrative/Scripts/ConversationManager.cs
Old Regex expression did not capture Character names with "." and "'". As a result characters with names like "Mr. Jones" or "Ab'ar" were not registering correctly.
I added . & ' characters into Regex. We may need to add some more characters in future.
=> Fix Regex for character names with "." & "'"

Assets/Fungus/Scripts/Editor/FlowchartWindow.cs
The flowchart now zooms in and out from either the center of the window or your mouse cursor. See: #225 
Only thing to note is that I'm sorry about the new ugly button to toggle the zoom setting. The toolbar mentioned in the issue will replace it soon :) (wanted to keep it a separate pull request to make things simpler).
=> Flowchart window improvements - zoom updates

Assets/Fungus/Scripts/Editor/FlowchartWindow.cs
See #225
Added duplicate, delete, and select all commands. Also added relevant commands to the block context menu and added new context menu with an add new block option.
In order to support a right-click context menu when clicking on the background while still being able to drag and pan, I moved showing the context menu from `EventType.ContextClick` to `EventType.MouseUp`, because `EventType.ContextClick` occurs on mouse down (at least on macOS). Unfortunately, there is some magic that happens before or during the `ContextClick` event, so the new context menus have slightly smaller text than before. I'm not really sure how to change this, but it seems fine regardless.
By the way--I did do the pro icons in another branch as discussed, but I want to try out one more idea before I do a PR …
=> Flowchart window improvements - keyboard shortcuts and context menu updates

Assets/Fungus/Scripts/Editor/FlowchartEditor.cs
Same as the previous pull request. I figured this might be good to do before another release since the button didn't work correctly any more.
=> Removed "Center View" button from FlowchartEditor

Assets/Fungus/Scripts/Components/Clickable2D.cs, Assets/Fungus/Scripts/Components/Draggable2D.cs, Assets/Fungus/Scripts/Components/EventHandler.cs, Assets/Fungus/Scripts/EventHandlers/DragCancelled.cs, Assets/Fungus/Scripts/EventHandlers/DragCompleted.cs, Assets/Fungus/Scripts/EventHandlers/DragEntered.cs, Assets/Fungus/Scripts/EventHandlers/DragExited.cs, Assets/Fungus/Scripts/EventHandlers/DragStarted.cs, Assets/Fungus/Scripts/EventHandlers/EventDispatcher.cs, Assets/Fungus/Scripts/EventHandlers/EventDispatcher.cs.meta, Assets/Fungus/Scripts/EventHandlers/FlowchartEnabled.cs, Assets/Fungus/Scripts/EventHandlers/GameStarted.cs, Assets/Fungus/Scripts/EventHandlers/ObjectClicked.cs
FindObjectsOfType is an expensive call and it is being called for each event in Draggable2D and Clickable2D. 
In order to avoid them I considered 2 options:
- Register and unregister the Handlers to the desired object, so the object would notify directly to the EventHanldlers. I've implemented this when the object needs to access the Handler.
- Register the handlers to an EventDispatcher and raise events from the object. I decided to implement this because with the EventDispatcher we can make it more isolated, only registered objects would listen to events, and multiple objects can listen to a certain event avoiding multiple references in objects. Also this way of dispatching events can be reused in multiple places.
=> Refactor EventHandler notification in order to avoid FindObjectsOfType calls

Assets/Fungus/Scripts/Utils/ConversationManager.cs, Assets/Tests/Narrative/ConversationTests.unity, Assets/Tests/Narrative/NarrativeTests.cs
Fix I discussed in Gitter chat.
If you hid a portrait twice, it would show up on the second hide. Now you have to specify a portrait to show before it will appear on stage again.
=> fix portrait hide bug in conversation

Assets/Fungus/Scripts/Commands/SavePoint.cs
You can use both the Custom and Block Name Keymodes for your Save Point key, which will produce something like (Block Name)_(Your Custom Key). You can even specify the character that separates the two.
I added this because when I named a Save Point step_1 in two different blocks, the wrong block got executed when I loaded it back. This makes it easier to have unique Save Point keys given that your block names are dissimilar.
=> New "Both" Keymode for Save Point command, use both block name and custom key together.

Assets/Fungus/Scripts/Components/SayDialog.cs
I often have to extend SayDialog per-game, and in particular often have to do work in Awake. While I was in there, I figured I'd bring the rest of the protected methods into virtual, as I can definitely see use cases for overriding `GetWriter` and `OnEnable`.
The following methods have been made virtual in this PR:
- Awake
- OnDestroy
- GetWriter
- GetCanvasGroup
- GetWriterAudio
- Start
- OnEnable
=> Make additional methods in SayDialog virtual

Assets/Fungus/Scripts/Editor/FlowchartWindow.cs
Added logic to handle destroying the blockdrawers when the target flowchart changes underneath them. A  nuclear option perhaps but solves Prefab Variable Dereferencing #618
=> Force recreate BlockEditors when target flowchart object changes

Assets/Fungus/Scripts/Editor/BlockEditor.cs
Added a text input box to the bottom of the Block Editor that allows user to type partial name of command and get a filtered list back that they can use up down arrows to navigate and enter to confirm.
Motivated by watching my students know they want an If or a Call but not having the muscle memory of where in the Generic Menu that is.
=> Command by name

Assets/Fungus/Scripts/Components/CameraManager.cs
I think this is the fastest way to fix it, and without affecting the current behaviour, by separating coroutines for panning and fading. 
Having both handles allowing to cancel one effect without affecting the other
=> fixes #612

Assets/Fungus/Scripts/Components/Flowchart.cs, Assets/Fungus/Scripts/Components/Localization.cs
Part of #638. May have been causing flowcharts and their referenced objects to be ineligible for GC at run-time and in editor.
Flowchart now registers and unregisters from SceneManager in OnEnable and OnDisable respectively
Localization now registers and unregisters from SceneManager in OnEnable and OnDisable respectively
=> SceneManager Delegate handling moved

Assets/Fungus/Scripts/Components/Flowchart.cs, Assets/Fungus/Scripts/Editor/FlowchartEditor.cs, Assets/Fungus/Scripts/Editor/FlowchartWindow.cs, Assets/Fungus/Scripts/Editor/FungusEditorPreferences.cs, Assets/Fungus/Scripts/Editor/VariableListAdaptor.cs
-Refactored DrawVariablesGUI
-Added bool to FungusEditorPreferences, that hides the variable list in the flowchart inspector
Disabled by default in the FungusEditorPreferences.
Speeds up workflows that require tweaking a number of Fungus Variables on a number of Flowcharts and inspecting Fungus Variable state if the FlowchartEditor is not visible (low resolution screen, behind game view etc.)
=> Added ability to show variable list in the Flowchart Inspector

Docs/fungus_docs/blocks.md
Number 6 of the section "Connections between Blocks" in blocks.md incorrectly referred to "Block2" instead of "Start". Changed to reflect what is actually displayed in 3_menu_call.png
=> Blocks.md Documentation Correction

Assets/Fungus/Scripts/Components/SaveMenu.cs
Threw in some infinite loop prevention when the SaveMenu is nested inside other GameObjects (and therefore the DontDestroyOnLoad method doesn't work). Also logs a more context-aware error when the SaveMenu is nested inside another GameObject.
This is my first time contributing. Please let me know if there's anything I could do better.
For further details, see [this issue](https://github.com/snozbot/fungus/issues/657#issuecomment-372126664).
=> Account for SaveMenu DontDestroyOnLoad problems

Assets/Fungus/Scripts/Commands/SetVariable.cs, Assets/Fungus/Scripts/Commands/VariableCondition.cs, Assets/Fungus/Scripts/Editor/SetVariableEditor.cs, Assets/Fungus/Scripts/Editor/VariableConditionEditor.cs, Assets/Fungus/Scripts/VariableTypes/AnimatorVariable.cs, Assets/Fungus/Scripts/VariableTypes/AudioSourceVariable.cs, Assets/Fungus/Scripts/VariableTypes/BooleanVariable.cs, Assets/Fungus/Scripts/VariableTypes/ColorVariable.cs, Assets/Fungus/Scripts/VariableTypes/FloatVariable.cs, Assets/Fungus/Scripts/VariableTypes/GameObjectVariable.cs, Assets/Fungus/Scripts/VariableTypes/IntegerVariable.cs, Assets/Fungus/Scripts/VariableTypes/MaterialVariable.cs, Assets/Fungus/Scripts/VariableTypes/ObjectVariable.cs, Assets/Fungus/Scripts/VariableTypes/Rigidbody2DVariable.cs, Assets/Fungus/Scripts/VariableTypes/SpriteVariable.cs, Assets/Fungus/Scripts/VariableTypes/StringVariable.cs, Assets/Fungus/Scripts/VariableTypes/TextureVariable.cs, Assets/Fungus/Scripts/VariableTypes/TransformVariable.cs, Assets/Fungus/Scripts/VariableTypes/Vector2Variable.cs, Assets/Fungus/Scripts/VariableTypes/Vector3Variable.cs
This PR adds basic comparison (equals and not equals) as well as basic assign functionality to the following variables:
- Animator
- AudioSource
- Color
- Material
- Object
- Rigidbody2D
- Sprite
- Texture
- Transform
- Vector2
- Vector3
Additionally, Color variables have set functionality for `+=`, `-=` and `*=`. Also, Vector2 and Vector3 variables have set functionality for `+=` and `-=`.
=> Set and compare other variables

Assets/Fungus/Scripts/Components/EventHandler.cs
Eventhandlers no longer fire when the flowchart is disabled as per #679
=> Disabled Flowcharts and EventHandlers

Assets/Fungus/Scripts/Commands/Conversation.cs, Assets/Fungus/Scripts/Utils/ConversationManager.cs, Assets/Fungus/Scripts/Utils/TextTagParser.cs, Assets/FungusExamples/Conversation/Conversation.unity, Docs/command_ref/narrative_commands.md, Docs/fungus_docs/conversation_system.md
Follow up from [the forum](http://fungusgames.com/forum#!/general:extending-the-conversation)
Allows a Conversation to control a similar set of options as a Say command.
-On the conversation command itself you can set defaults for fade, wait for input, wait delay, extend previous
-Each item in the conversation can now also set [clear | noclear] [wait | nowait] [fade | nofade] before the story text
=> Conversation options

Assets/Fungus/Scripts/Components/NarrativeLog.cs
-previously caused nullref in TheFacility Demo Scene
=> NarrativeLog is tolerant of null Name or Story fields

Assets/Fungus/Scripts/Commands/Condition.cs, Assets/Fungus/Scripts/Components/Block.cs
-Corrects elifs from pairing incorrectly with nested ifs prior to themselves
-Thanks to Wolfrug on the forum http://fungusgames.com/forum#!/support-questions:if-else-bug
=> ElseIfs now confirm that the previous condition was at the same indent as themselves.

Assets/Fungus/Scripts/Utils/ConversationManager.cs
-Allows conversation to use portraits like calling-neutral
=> Conversation Manager Regex now allows - and _ within say params group.

Docs/fungus_docs/blocks.md, Docs/fungus_docs/glossary.md
Currently the documentation refers to blocks as either rectangles or polygons. This is a strange choice as rectangles are subset of polygons; a rectangle is a type of polygon. Thus, identifying the choice blocks as polygons is unnecessarily confusing, especially for the color blind. Given that the choice blocks are six-sided, they can be more specifically identified as hexagons.
=> Specifically identify choice blocks as hexagons 

Assets/Fungus/Scripts/Components/Flowchart.cs, Assets/Fungus/Scripts/Components/Localization.cs, Assets/Fungus/Scripts/Utils/ConversationManager.cs, Assets/Fungus/Scripts/Utils/TextTagParser.cs, Assets/Tests/StringSubstitution/Editor/FungusConversationParseTests.cs, Assets/Tests/StringSubstitution/Editor/FungusConversationParseTests.cs.meta
Fix prompted by report on the forum, [link](http://fungusgames.com/forum#!/general:use-of-colon-in-conversatio).
Minor change to Conversation regex grouping
Added Conversation Tests for existing functionality and multi colon
-Conversation Parse refactor to allow for static testing
Moved all regex strings across fungus to const strings
=> Conversation text can now contain colons within the text body itself

Assets/Fungus/Scripts/Editor/BlockEditor.cs, Assets/Fungus/Scripts/Editor/BlockInspector.cs
Changes Block inspector and editor to support 2019.1a13.
- Block name position has changed.
- use of GUILayout.*Area removed as it was the primary cause of problems in 2019
This layout is now consistent and usable across 2017.4, 2018.3, 2019.1a13
closes #724
=> 2019 1a13 support

Assets/Fungus/Scripts/Commands/FadeUI.cs, Assets/Fungus/Scripts/Commands/GetText.cs, Assets/Fungus/Scripts/Commands/SetText.cs, Assets/Fungus/Scripts/Components/NarrativeLogMenu.cs, Assets/Fungus/Scripts/Utils/TextAdapter.cs
Based on feedback from linkad333 on the forum, [link](http://fungusgames.com/forum#!/general:text-mesh-pro-w-fungus-fun). 
-Support use of TMPro in Set Text, Get Text and Narrative Log Menu via use of TextAdapter
-FadeUI also checks for CanvasGroups and if 2018_1_OR_NEWER will check for TMP_Text components too
-TextAdapter uses 2018_1_OR_NEWER for more thorough support of TMPro such as color and rich text operations
=> TMPro support for Get/Set Text, FadeUI & NarrativeLog

Assets/Fungus/Scripts/Editor/PopupContent/CommandSelectorPopupWindowContent.cs, Assets/Fungus/Scripts/Editor/PopupContent/EventSelectorPopupWindowContent.cs, Assets/Fungus/Scripts/Editor/PopupContent/VariableSelectPopupWindowContent.cs
Convert Variable Type list, EventHandler Type list and Command Type list to property
-force init cache of access, this solves the 'Cannot add variable' style errors that have been reported
=> Editor List Caching Fix

Assets/Fungus/Scripts/Editor/CharacterEditor.cs
Prevents it stealing focus from ContextMenus
Fix #751
=> Character only sets self dirty if change detected

Assets/Fungus/Scripts/Components/MenuDialog.cs
-Menu item requested when there are non left
-Timer requested when none is available
Related to forum issues raised here, [link](http://fungusgames.com/forum#!/general:why-doesnt-my-menu-option)
=> Added warnings when MenuDialog

Assets/Fungus/Scripts/Editor/BlockInspector.cs
On some newer versions of Unity, the BlockInspector will crash whenever the user selects a block in the flowchart window.
The inspector window will not populate, and the console will throw null reference errors every editor frame as long as the block is selected.
This is due to `activeBlockEditor` never getting instantiated properly. I suspect that this is due to recent API changes that made `Editor.CreateEditor(block)` create a generic Editor object, instead of a BlockEditor. Since the object is not actually the extended type, the reference becomes null after being cast using `as`.
The fix is to change this line to `Editor.CreateEditor(block, typeof(BlockEditor))`
This overload parameter ensures that the object is instantiated using the correct type. This fix should work for all …
=> Fix for BlockInspector Crash

Assets/Fungus/Scripts/Editor/BlockEditor.cs
- Fixes a null ref caused changes in Unity Editor UI where EditorWindow.focusedWindow would be null
=> Fallback for Command Search Popup height

Assets/Fungus/Scripts/Editor/EditorExtensions.cs
-Uses TypeCache if available
Required to support use of asmdef, also would fix #734
=> EditorUtils.FindDerivedTypes now finds within ALL assembles

Assets/Fungus/Scripts/Components/Block.cs, Assets/Fungus/Scripts/Editor/EditorZoomArea.cs, Assets/Fungus/Scripts/Editor/FlowchartWindow.cs, Assets/Fungus/Scripts/Editor/FungusEditorPreferences.cs
Controlled via toggle in Fungus Editor Prefs.
Snaps and aligns blocks to underlying grid in the flowchart window.
More caches for styles and lists to reduce allocations during block drawing
=> Add option to Grid Snap block in flowchart window

Assets/Fungus/Scripts/Editor/HierarchyIcons.cs
The removed line was not functioning as intended, it was covering the disclosure triangle of a parent GO with the mushroom icon if that parent GO also had a flowchart component.
I'm sure there was a reason for this logic change, so I've left the if cases intact, but this was necessary in my own project so I thought I'd share it.
Tested locally and works fine. This is my first ever community git contribution, so apologies if I've committed a faux pa!
=> Heirarchy Icon placement bug in newer Unity versions

Assets/Fungus/Scripts/Commands/Portrait.cs, Assets/Fungus/Scripts/Components/PortraitController.cs, Assets/Fungus/Scripts/Components/Stage.cs, Assets/Fungus/Scripts/Utils/PortraitUtils.cs
Character PortraitState now contains all the character portraits underneath a single container object, at all times. The holder moves and the individual portraits fade in and out. Previous method created and destroyed an object for the portrait as they were requested, the previous method was susceptible to the 'white square' UI Image bug.
=> Portrait reworked

Assets/Fungus/Scripts/Components/Variable.cs, Assets/Fungus/Scripts/Utils/AllVariableTypes.cs, Assets/Fungus/Scripts/VariableTypes/AnimatorVariable.cs, Assets/Fungus/Scripts/VariableTypes/AudioSourceVariable.cs, Assets/Fungus/Scripts/VariableTypes/CollectionVariable.cs, Assets/Fungus/Scripts/VariableTypes/Collider2DVariable.cs, Assets/Fungus/Scripts/VariableTypes/ColliderVariable.cs, Assets/Fungus/Scripts/VariableTypes/GameObjectVariable.cs, Assets/Fungus/Scripts/VariableTypes/MaterialVariable.cs, Assets/Fungus/Scripts/VariableTypes/ObjectVariable.cs, Assets/Fungus/Scripts/VariableTypes/Rigidbody2DVariable.cs, Assets/Fungus/Scripts/VariableTypes/RigidbodyVariable.cs, Assets/Fungus/Scripts/VariableTypes/SpriteVariable.cs, Assets/Fungus/Scripts/VariableTypes/TextureVariable.cs, Assets/Fungus/Scripts/VariableTypes/TransformVariable.cs
FungusVariables that are object references now return string of Null rather than string of empty when descriptions are requested. As the result of these calls is often shown to the user in the inspector with in blocks or commands empty made the results less easy to understand.
eg "PlayerGO == " is less readable than "PlayerGO == Null"
=> Change to Show Null for FungusVariables

Assets/Fungus/Scripts/Editor/ViewEditor.cs
I just got into a project that had the editor run VERY slow. I noticed there was thousands of calls to DrawGizmo even if there wasn't much gizmos in the scene. I narrowed this down to Fungus.EditorUtils.ViewEditor.RenderCustomGizmo which was really surprising because Fungus was not used in the scene I was working on.
Has it turns out, the DrawGizmo attribute was being called for ALL objects in the scene and there is more than ten thousand objects in this scene so it was crippling the performance of the editor. This was easy to fix: just filter out all the objects that don't have the View component by using the second constructor of the DrawGizmo attribute.
Editor performance being crippled if there is MANY (10000+) objects in a scene even if Fungus is not being used in that scene.
Normal …
=> Fixed massive slowdown in editor when there is MANY objects in the scene

Assets/Fungus/Scripts/Commands/LoadVariable.cs
Bug fix.
When you try loading an int variable with an invalid key, it gets set to 0 instead of being left alone
Relevant issue: #867 
LoadVariable checks if the key is valid before making any changes, regardless of variable type.
- My change modifies the runtime execution/behaviour of the Load Variable command
=> Fixed issue with variables being modified when the key isn't valid

Assets/Fungus/Scripts/Components/PortraitController.cs, Assets/Tests/Portrait_MoveToFront.unity, Assets/Tests/Portrait_MoveToFront.unity.meta
Fixes #869 
- If adding prefabs or scenes, please make them in the oldest supported version of Unity possible (to ensure they are able to run in the Compatability release)
I used 2020 to create a scene but it does open in 2019.4.8f1.
2018.4.26 doesn't open the project without error (something about packages) so maybe that's not supported anyways? Can't find documentation on which unity versions are supported by Fungus.
Bugfix for #869 
Move To Front does nothing
Move To Front moves character's portraits parent to the front
- My change modifies the runtime execution/behaviour of existing Fungus Features. e.g., Say, Menus, Portraits, etc.
- My change adds 1 test scene
=> Portrait Move To Front Fixed

Assets/Fungus/Scripts/Editor/CommandListAdaptor.cs, Assets/Fungus/Scripts/Editor/FlowchartWindow.cs, Assets/Fungus/Scripts/Editor/FungusEditorPreferences.cs
CommandListAdapter items and Blocks in flowchartwindow have configurable tints in fungus editor preferences.
Adding simple tinting for elements of Fungus UI as per close #868 
In the Fungus Editor Preferences the user can now configure a tint colour for the CommandList in the Block Inspector and a tint for the Block icons in the Flowchart Window.
These type of tints are easy to integrate and should remain easy to maintain. I'll wait for feedback before mering this PR in case there are more elements that are requested.
=> Add Simple Tint preferences

Assets/Fungus/Scripts/Commands/MoveAdd.cs, Assets/Fungus/Scripts/Commands/MoveFrom.cs, Assets/Fungus/Scripts/Commands/MoveTo.cs, Assets/Fungus/Scripts/Commands/PunchPosition.cs, Assets/Fungus/Scripts/Commands/PunchRotation.cs, Assets/Fungus/Scripts/Commands/PunchScale.cs, Assets/Fungus/Scripts/Commands/RotateAdd.cs, Assets/Fungus/Scripts/Commands/RotateFrom.cs, Assets/Fungus/Scripts/Commands/RotateTo.cs, Assets/Fungus/Scripts/Commands/ScaleAdd.cs, Assets/Fungus/Scripts/Commands/ScaleFrom.cs, Assets/Fungus/Scripts/Commands/ScaleTo.cs, Assets/Fungus/Scripts/Editor/BasePopupWindowContent.cs, Assets/Fungus/Scripts/Editor/CommandEditor.cs, Assets/Fungus/Scripts/Editor/CommandListAdaptor.cs, Assets/Fungus/Scripts/Editor/EventHandlerEditor.cs, Assets/Fungus/Scripts/Editor/FlowchartWindow.cs, Assets/Fungus/Scripts/Editor/PopupContent/CommandSelectorPopupWindowContent.cs, Assets/Fungus/Scripts/Editor/PopupContent/EventSelectorPopupWindowContent.cs, Assets/Fungus/Scripts/Editor/PopupContent/VariableSelectPopupWindowContent.cs, Assets/Fungus/Scripts/Editor/VariableListAdaptor.cs, Assets/Fungus/Scripts/Utils/FungusConstants.cs
Can be added to Commands, Variables, and EventHandlers. Resulting in a warning box when using them and showing a yellow [DEP] prefacing them.
Add Obsolete to iTween tween commands that have existing LeanTween alternates
Closes #858
=> Add Support for Obsolete attribute

Assets/Fungus/Scripts/Editor/BlockEditor.cs
Added ability to cycle Editor block commands with up/down arrow (already possible with pagedown/pageup)
Related to #879 
Navigating block commands in the editor is only possible with PageUp and PageDown keys.
Navigating block commands in the editor is only possible with PageUp and PageDown keys AND Up and Down arrow keys.
- My change modifies the workflow/editing of flowcharts/blocks/commands etc.
=> Update BlockEditor.cs to support up/down key navigation

Assets/Fungus/Scripts/Editor/BlockEditor.cs, Assets/Fungus/Scripts/Editor/CommandEditor.cs, Assets/Fungus/Scripts/Editor/CommandListAdaptor.cs, Assets/Fungus/Scripts/Editor/EventHandlerEditor.cs, Assets/Fungus/Scripts/Editor/FungusEditorPreferences.cs, Assets/Fungus/Scripts/EventHandlers/ButtonClicked.cs, Assets/Fungus/Scripts/EventHandlers/DragCancelled.cs, Assets/Fungus/Scripts/EventHandlers/DragCompleted.cs, Assets/Fungus/Scripts/EventHandlers/DragEntered.cs, Assets/Fungus/Scripts/EventHandlers/DragExited.cs, Assets/Fungus/Scripts/EventHandlers/DragStarted.cs, Assets/Fungus/Scripts/EventHandlers/EndEdit.cs, Assets/Fungus/Scripts/EventHandlers/KeyPressed.cs, Assets/Fungus/Scripts/EventHandlers/ObjectClicked.cs, Assets/Fungus/Scripts/EventHandlers/SliderChanged.cs, Assets/Fungus/Scripts/EventHandlers/ToggleChanged.cs
EventHandlers GetSummary is now shown in the inspector.
Add editor pref to hide eventhandler and command info helpboxes
closes #834 
EventHandlers have a GetSummary much like a Command, but it was mostly unused.
GetSummary was not used.
- EventHandlers returning content in GetSummary are shown in a helpbox, If returning Error: that box is an error box.
- This also adds the ability to toggle off the default HelpBoxes for EventHandlers and Commands in the block inspector, this is found in the FungusPreferences.
- My change require modifcations or additions to documentation.
- Manually update to the EventHandle summary.
Existing EventHandlers have had
=> Add EventHandler Error Box

Assets/Fungus/Scripts/Components/Block.cs
closes #882
Allows for easier tracking down of exceptions caused by Commands within Fungus.
Fungus allows exceptions to bubble all the way up to unity for capture and log into Unity Console. This is troublesome when there are many Flowcharts, many Blocks or Many similar Commands as it does not identify which command in which block, in which flowchart.
- Blocks now catch, exceptions from Command.Execute. LogError their LocationIdentifier to console and rethrow the exception
- This results in 2 exception logs for each command exception but makes them far easier to trace and does not alter the existing paradigm of allowing exceptions to bubble all the way up to Unity.
=> Add Log of Location for Command Execute Exceptions

Assets/Fungus/Scripts/Commands/LeanTween/ShakeCameraLean.cs, Assets/Fungus/Scripts/Commands/LeanTween/ShakeCameraLean.cs.meta, Assets/Fungus/Scripts/Commands/LeanTween/ShakeLean.cs, Assets/Fungus/Scripts/Commands/LeanTween/ShakeLean.cs.meta, Assets/Fungus/Scripts/Commands/LeanTween/ShakePositionLean.cs, Assets/Fungus/Scripts/Commands/LeanTween/ShakePositionLean.cs.meta, Assets/Fungus/Scripts/Commands/LeanTween/ShakeRotationLean.cs, Assets/Fungus/Scripts/Commands/LeanTween/ShakeRotationLean.cs.meta, Assets/Fungus/Scripts/Commands/LeanTween/ShakeScaleLean.cs, Assets/Fungus/Scripts/Commands/LeanTween/ShakeScaleLean.cs.meta, Assets/Fungus/Scripts/Commands/ShakeCamera.cs, Assets/Fungus/Scripts/Commands/ShakePosition.cs, Assets/Fungus/Scripts/Commands/ShakeRotation.cs, Assets/Fungus/Scripts/Commands/ShakeScale.cs, Assets/Fungus/Scripts/Components/Writer.cs, Assets/Fungus/Scripts/Utils/LeanTweenHelpers.cs, Assets/Fungus/Scripts/Utils/LeanTweenHelpers.cs.meta, Assets/FungusExamples/LeanTween/LeanTween.unity
Replace Fungus' internal use of iTween for shakes with a LeanTween based alternative.
Add LeanTween based Shake alternates for all iTween shake commands and mark them as Deprecated.
Add Shakes to LeanTween FungusExample
Follows #853, Seeks to remove all remaining internal use of iTween directly by Fungus.
Shakes used iTween shake internally.
- No change to user. Fungus internally uses a LeanTween based alternate for shakes.
- LeanTween based Shake commands have been added and the existing iTween shake commands have been marked as deprecated
- My change require modifcations or additions to documentation (regeneration of auto gen doco)
- My change modifies existing FungusExamples
=> Add LeanTween Shake alternatives

Assets/Fungus/Scripts/Commands/FromString.cs, Assets/Fungus/Scripts/Commands/InvokeMethod.cs, Assets/Fungus/Scripts/Commands/SetCollider.cs, Assets/Fungus/Scripts/Utils/EventDispatcher.cs
Remove bespoke exception handling in cases where block command catch can do it better.
See #882 
The Awake tries to catch and logbut its info is not overly helpful.
- the awake and onenter of the InvokeMethod will now both result in a rethrow and a logerror with the location information
- other commands with custom try catch inside OnEnter have been removed in favour of calling block handling it.
=> Add info to logerror for InvokeMethod Awake

Assets/Fungus/Scripts/Editor/FlowchartWindow.cs
Fix bug where Ctrl+D will duplicate selected blocks twice.
1. Select blocks
2. Press Ctrl+D to duplicate
3. Every selected blocks will be duplicated twice (one of them hidden behind the other)
- Union blocks before copying
=> Fix double duplication of blocks with Ctrl+D

Assets/Fungus/Scripts/Components/WriterAudio.cs
While doing lipsync, I ran into the fact that it is impossible to understand when the voice over clip finishes its playback.
After playing a voice, the GetSecondsRemaining returns its full duration audio clip.
After the voice clip has finished playing, the number of seconds remaining becomes 0.
=> Fix GetSecondsRemaining

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, Assets/Fungus/Scripts/Components/DialogInput.cs, README.md
Similar to ClickOnDialog for dialog progression. It has capability to delay the next input, while ClickAnywhere does not
nextClickDelay does not work with ClickAnywhere
nextClickDelay now works with ClickAnywhere
- My change does not require modifcations or additions to documentation
=> Make nextClickDelay works with ClickAnywhere 

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, Assets/Fungus/Scripts/Components/DialogInput.cs, Assets/Fungus/Scripts/Components/Writer.cs, README.md
Currently the DialogInput will always set nextlineinputflag to true when clicking mouse multiple times even if there's no writing activity on screen, thus making the next Say auto-completed. Even mouse clicks when there's menu choices will trigger the next Say to be auto-completed.
This may solves:
https://github.com/snozbot/fungus/issues/910
https://github.com/snozbot/fungus/issues/954
Every mouse clicks will set nextlineinputflag  to true
Add condition to SetNextLineFlag so it won't always be true on button presses when there's no writing activity on screen or when the text is already completed.
Before:  
https://user-images.githubusercontent.com/64100867/106449306-69653d00-64b6-11eb-8c3b-db07ff979a9c.mp4
After:
https://user-images.githubusercontent.com/64100867/106449364-7aae4980-64b6-1 …
=> nextLineInputFlagWon't Always Be True On Mouse Clicks

Assets/Fungus/Docs/CHANGELOG.txt, Assets/Fungus/Scripts/Utils/TextAdapter.cs
Ensures subsequent calls to tmpro related elements, such as revealed characters, are not stale.
Relates to #910 and #954
=> Add ForceMeshUpdate to TextAdapter

Assets/Fungus/Scripts/Components/NarrativeLog.cs, Assets/Fungus/Scripts/Components/NarrativeLogMenu.cs
Fixes 65000 vertices limit by limiting character shown in NarrativeLog
It will throw **ArgumentException: Mesh can not have more than 65000 vertices** if NarrativeLog texts over 65000 vertices
The text will get truncated to default 10000 characters (users can change the characters limit) and a tripple-dots prefix will be added as indicator that it was truncated
**BEFORE**  
https://user-images.githubusercontent.com/64100867/121877827-3faa0580-cd35-11eb-8fba-3f2e83578e8c.mp4
**AFTER**  
https://user-images.githubusercontent.com/64100867/121878023-708a3a80-cd35-11eb-9a30-881bf98f9f23.mp4
Edit: Description edit
Relates to https://github.com/snozbot/fungus/issues/945
=> Limit Characters Shown In NarrativeLog to Avoid 65000 Vertices Limit
