Assets/Fungus/Narrative/Scripts/Localization.cs
Assets/Tests/Localisation/CSV/localization_dottest.csv
Assets/Tests/Localisation/CSV/localization_dottest.csv.meta
Assets/Tests/Localisation/LocalisationTests.unity

Fix for localisation init order issue

Fix localization parsing

---

Assets/Fungus/Narrative/Resources/SayDialog.prefab
Assets/Fungus/Narrative/Scripts/Commands/Say.cs
Assets/Fungus/Narrative/Scripts/SayDialog.cs
Assets/Tests/Narrative/NarrativeTests.unity

Say Dialog automatically deactivates when alpha is 0

Fit storytext to image

---

Assets/Fungus/Camera/Scripts/Commands/ShakeCamera.cs
Assets/Tests/Tweening.meta
Assets/Tests/Tweening/TweeningTests.unity
Assets/Tests/Tweening/TweeningTests.unity.meta

Using a proper iTween callback instead of using Invoke.
Added integration test.

Fixed Shake Camera timing issue #137

---

Assets/Fungus/Narrative/Scripts/SayDialog.cs
Assets/Tests/Localisation/LocalisationTests.unity
Assets/Tests/Narrative/NarrativeTests.unity

Tested all example scenes from previous Fungus version.
Everything works fine except for expected issues from changes to the
Say Dialog. The Facility scene no longer works because of the custom
Say Dialogs.

Backwards compatibility with 2.1

---

Assets/Fungus/Sprite/Scripts/Commands/SetLayerOrder.cs
Assets/Fungus/Sprite/Scripts/Commands/SetLayerOrder.cs.meta
Assets/Tests/Sprite/SpriteTests.unity

Applies to all Renderers (incl. Mesh & Sprite)

Added Set Sorting Layer command

---

Assets/Fungus/Flowchart/Editor/BlockEditor.cs
Assets/Tests/Commands.meta
Assets/Tests/Commands/FailTest.cs
Assets/Tests/Commands/FailTest.cs.meta
Assets/Tests/Commands/PassTest.cs
Assets/Tests/Commands/PassTest.cs.meta
Assets/Tests/Scripting/Scripting.unity

Added FailTest and PassTest commands

Added test for Save Variable / Load Variable

---

Assets/Fungus/Narrative/Scripts/SayDialog.cs
Assets/Fungus/UI/Scripts/Writer.cs
Assets/Tests/Narrative/NarrativeTests.unity

Stop any previous Say call before executing the new one.
The Say Dialog Wait and Wait for Input methods now exit immediately if
the exit tag is set.

Fixed: Concurrent Say calls cause Say Dialog to freeze up #156

---

Assets/Fungus/Flowchart/Editor/BlockEditor.cs
Assets/Fungus/Flowchart/Editor/FlowchartEditor.cs
Assets/Fungus/Flowchart/Editor/FlowchartMenuItems.cs
Assets/Fungus/Flowchart/Resources/Flowchart.prefab
Assets/Fungus/Flowchart/Scripts/Flowchart.cs

Also added safety cleanup code to remove null items in variable list in
cleanup.

Flowchart prefabs

---

Assets/Fungus/UI/Scripts/TextTagParser.cs
Assets/Fungus/UI/Scripts/Writer.cs
Assets/Tests/UI/DummyText.cs
Assets/Tests/UI/DummyText.cs.meta
Assets/Tests/UI/Editor/TextTagParserTests.cs
Assets/Tests/UI/TextTests.unity

Text tags now support multiple parameters.
Write command now works with Text Mesh Pro text objects.
Writer.InstantComplete property controls click-to-complete writing.
Shake tag shakes camera instead of Writer game object.

Misc improvements to the Writer system

---

Assets/Fungus/Flowchart/Resources/Flowchart.prefab

Removed say command from Flowchart prefab

---

Assets/Fungus/iTween/Scripts/Commands/iTweenCommand.cs

The fix is to make the stopping behaviour option via a property

Fixed iTween commands on the same gameobject can conflict #342

---

Assets/Fungus/Audio/Scripts/Commands/PlayMusic.cs
Assets/Fungus/Audio/Scripts/MusicController.cs
Assets/Tests/Audio/AudioTests.unity

Play Music call doesn't restart if same music already playing

---

Assets/Fungus/Thirdparty/FungusLua/Resources/Lua/fungus.txt
Assets/Fungus/Thirdparty/FungusLua/Scripts/LuaUtils.cs

This doesn’t really do anything to solve the timescale issues with
Fungus, so removing it for simplicity.

Removed timescale functions

---

Assets/Fungus/Flowchart/Editor/BlockEditor.cs
Assets/Fungus/Thirdparty/FungusLua/Scripts/LuaUtils.cs

In the Block Editor, when you have only one command selected and you're in play mode, it will give you the option to play from the selected command. If it's from a block that isn't executing, it will stop the current executing block then start the selected one.

Add "Play from Selected Command" to the BlockEditor ContextMenu

---

Assets/Fungus/Narrative/Scripts/Character.cs
Assets/Fungus/Narrative/Scripts/DialogInput.cs
Assets/Fungus/Narrative/Scripts/PortraitController.cs
Assets/Fungus/Narrative/Scripts/Stage.cs
Assets/Fungus/Thirdparty/FungusLua/Resources/Lua/fungus.txt
Assets/Fungus/Thirdparty/FungusLua/Scripts/ConversationManager.cs
Assets/Fungus/Thirdparty/FungusLua/Scripts/ConversationManager.cs.meta
Assets/Fungus/Thirdparty/FungusLua/Scripts/LuaUtils.cs
Assets/FungusExamples/FungusLua/Narrative/PortaitControlExample.unity

Started a new pull request to start over with our new idea of using luautils.conversation[[ ]]

Create Conversation Function in LuaUtils

---

Assets/Fungus/Narrative/Scripts/ConversationManager.cs
Assets/FungusExamples/Conversation/Conversation.unity

Whatever direction the character is facing, flip them to the opposite direction. Doesn't work if they are facing forward.

Add Flip option to conversation system

---

Assets/Fungus/Scripts/Editor/EditorZoomArea.cs
Assets/Fungus/Scripts/Editor/FlowchartWindow.cs

See: #225 
This replaces the floating UI buttons with a toolbar like in other Unity windows. I added a few buttons that were mentioned in the issue as well (min zoom, max zoom, center).
Notes:
- I personally don't feel like I'd use the min/max zoom buttons ever, but I added them in since someone else requested them. Do you think they add unnecessary clutter?
- The toolbar will get filled with other UI that was requested in the issue, but I didn't want to tangle up the toolbar pull request with each feature that will it for UI. That said, if you don't like how it looks now, I don't want to bank on future updates validating it.

Flowchart window improvements - toolbar

---

Assets/Fungus/Scripts/Editor/EventWindow.cs
Assets/Fungus/Scripts/Editor/EventWindow.cs.meta
Assets/Fungus/Scripts/Editor/FlowchartWindow.cs
Assets/Materials.meta

This is a lot of the same code from the other pull request, except I tried to avoid doing any optimizations. It's mostly just refactoring how the events are handled and also some misc. cleanup, e.g. keeping the flowchart as a class variable. It's still a bigger PR than I'd hoped. It's hard to isolate stuff in editor code :(.

Flowchart window event refactor

---

Assets/Fungus/Scripts/Utils/ConversationManager.cs

fixes #591 
I wasn't sure how to add a test for this bug, but it might not be necessary...

Stops Conversation Audio

---

Assets/Fungus/Scripts/Components/PortraitController.cs
Assets/Fungus/Scripts/Components/Stage.cs
Assets/Tests/Narrative/ConversationTests.unity

Add portrait DimColor, then user can choose which color they want to dim the portrait, not only 50% grey.
(I am totally newbie to github, please feel free to tell me any suggestions.)

Add portrait DimColor

---

Assets/Fungus/Scripts/Commands/Condition.cs
Assets/Fungus/Scripts/Commands/LuaCondition.cs
Assets/Fungus/Scripts/Commands/LuaCondition.cs.meta
Assets/Fungus/Scripts/Commands/LuaElseIf.cs
Assets/Fungus/Scripts/Commands/LuaElseIf.cs.meta
Assets/Fungus/Scripts/Commands/LuaIf.cs
Assets/Fungus/Scripts/Commands/LuaIf.cs.meta
Assets/Fungus/Scripts/Commands/VariableCondition.cs
Assets/Fungus/Scripts/Commands/VariableCondition.cs.meta
Assets/Tests/Scripting/Scripting.unity

Allow Lua to be used in Conditional commands (as `LuaIf` and `LuaElseIf`), and allow Conditional commands of multiple types to see and respond to each other!
This PR comes with at least one nasty compromise: the `Condition#IsElseIf` property is kind of a bummer, but its addition allowed me to preserve the class hierarchy and DRY out the `ElseIf` code quite nicely (also reused in `LuaElseIf`).
Tests are written and pass:

Lua conditional commands

---

Assets/Fungus/Scripts/Commands/LeanTween.meta
Assets/Fungus/Scripts/Commands/LeanTween/BaseLeanTweenCommand.cs
Assets/Fungus/Scripts/Commands/LeanTween/BaseLeanTweenCommand.cs.meta
Assets/Fungus/Scripts/Commands/LeanTween/MoveLean.cs
Assets/Fungus/Scripts/Commands/LeanTween/MoveLean.cs.meta
Assets/Fungus/Scripts/Commands/LeanTween/RotateLean.cs
Assets/Fungus/Scripts/Commands/LeanTween/RotateLean.cs.meta
Assets/Fungus/Scripts/Commands/LeanTween/ScaleLean.cs
Assets/Fungus/Scripts/Commands/LeanTween/ScaleLean.cs.meta
Assets/Fungus/Scripts/Commands/LeanTween/StopTweensLean.cs
Assets/Fungus/Scripts/Commands/LeanTween/StopTweensLean.cs.meta
Assets/FungusExamples/LeanTween.meta
Assets/FungusExamples/LeanTween/LeanTween.unity
Assets/FungusExamples/LeanTween/LeanTween.unity.meta

#616 
Some LeanTween alternates to iTween commands

Lean tween commands

---

Assets/Fungus/Scripts/Commands/SpawnObject.cs
Assets/Fungus/Scripts/Components/Command.cs
Assets/Fungus/Scripts/Editor/CommandEditor.cs

SpawnObject can now also be found under GameObject/Instantiate

Allow multiple CommandInfos to be added to a class

---

Assets/Fungus/Scripts/Components/SaveManager.cs

SaveManager now uses json files in a FungusSaves sub directory for all platforms but webplayer & webgl which still use playerprefs
#634

SaveManager use persistentStore 

---

Assets/Fungus/Scripts/Commands/Menu.cs
Assets/Fungus/Scripts/Commands/MenuShuffle.cs
Assets/Fungus/Scripts/Commands/MenuShuffle.cs.meta
Assets/Fungus/Scripts/Components/MenuDialog.cs
Assets/Fungus/Scripts/Editor/MenuEditor.cs
Assets/FungusExamples/MenuShuffle.meta
Assets/FungusExamples/MenuShuffle/MenuShuffle.unity
Assets/FungusExamples/MenuShuffle/MenuShuffle.unity.meta
Docs/command_ref/narrative_commands.md

-refactor menudialogue to track items that are hidden
Menu Fungus Command now has a hideThisOption boolean
Updated narrative_commands doco to match
#267

Added MenuShuffle Fungus Command and a demo scene

---

Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/Batch.cs

Just one line change :)
But avoids error message on newer versions of Unity3D

Updated Batch for newer versions of Unity3D web player

---

Assets/Fungus/Scripts/Commands/SetVariable.cs
Assets/Fungus/Scripts/Commands/VariableCondition.cs
Assets/Fungus/Scripts/Components/Variable.cs
Assets/Fungus/Scripts/Editor/SetVariableEditor.cs
Assets/Fungus/Scripts/Editor/VariableConditionEditor.cs
Assets/Fungus/Scripts/Editor/VariableEditor.cs
Assets/Fungus/Scripts/VariableTypes/BooleanVariable.cs
Assets/Fungus/Scripts/VariableTypes/FloatVariable.cs
Assets/Fungus/Scripts/VariableTypes/GameObjectVariable.cs
Assets/Fungus/Scripts/VariableTypes/IntegerVariable.cs
Assets/Fungus/Scripts/VariableTypes/StringVariable.cs

**Important Note:** Although this is technically not fully dependant on it, this PR is built on top of the changes from #665 (they share some commits). Please review #665 first.
The main point of this refactor is to make it easier to add variable comparison options
for new variables and to better match the set variable system.

Refactor compare variable system and add comparison for GameObjects

---

Assets/Fungus/Scripts/Commands/StopFlowchart.cs

-as reported on the forum by inarval http://fungusgames.com/forum#!/general:stopflowchart-not-continuin

StopFlowchart can Continue now

---

Assets/Fungus/Scripts/Commands/Input/GetKey.cs
Assets/Fungus/Scripts/Commands/Input/GetKey.cs.meta
Assets/FungusExamples/Playground/Defender.unity
Assets/FungusExamples/Playground/Football.unity
Assets/FungusExamples/Playground/Lander.unity
Assets/FungusExamples/Playground/Prefabs/Laser.prefab
Assets/FungusExamples/Playground/Prefabs/P1.prefab
Docs/command_ref/input_commands.md

-Supports positive and negative keybindings output to a bool, float or int
-Supports checking for pressed, release and current state
-Uses keycode with optional fallback to key name
Updated playground demos
-Football uses GetKey instead of GetAxis (get axis was failing in some packages as inputmanager axis were not imported)
-Defender had a bug due to a change in how unity syncs 'up' between transform and rb2d

Added GetKey fungus command.

---

Assets/Fungus/Scripts/Commands/Menu.cs
Assets/Fungus/Scripts/Components/MenuDialog.cs
Assets/Fungus/Scripts/Components/Writer.cs
Assets/Fungus/Scripts/Utils/TextVariationHandler.cs
Assets/Fungus/Scripts/Utils/TextVariationHandler.cs.meta
Assets/FungusExamples/VariationText.meta
Assets/FungusExamples/VariationText/TextVariation.unity
Assets/FungusExamples/VariationText/TextVariation.unity.meta
Assets/Tests/StringSubstitution/Editor.meta
Assets/Tests/StringSubstitution/Editor/FungusTextVariationSelectionTests.cs
Assets/Tests/StringSubstitution/Editor/FungusTextVariationSelectionTests.cs.meta

Writer and Menu now use TextVariationHandler which allows for [ink style text selection](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#6-variable-text).
Sections are marked with []
sub elements divided by |
These are sequences by default but can be made to loop, once only or random each time with control characters. They can also be nested within each other.

Variable text selection

---

Assets/Fungus/Scripts/Editor/VariableReferenceDrawer.cs
Assets/Fungus/Scripts/Editor/VariableReferenceDrawer.cs.meta
Assets/Fungus/Scripts/Utils/VariableReference.cs
Assets/Fungus/Scripts/Utils/VariableReference.cs.meta
Assets/FungusExamples/FirstPerson/FirstPersonDemo.unity
Assets/FungusExamples/FirstPerson/Scripts/LookingAtDoor.cs

allows for selecting a flowchart and targeting a specific fungus variable for use from c# via the inspector with a drawer similar to that of BlockReference.
Added simple usage to FirstPerson Demo

Variable reference struct

---

Assets/Fungus/Scripts/Commands/Call.cs
Assets/Fungus/Scripts/Components/Block.cs
Assets/Fungus/Scripts/Components/Flowchart.cs
Assets/Tests/Scripting/RecursiveCall.unity
Assets/Tests/Scripting/RecursiveCall.unity.meta

Relates to [this forum thread](http://fungusgames.com/forum#!/support-questions:bug-with-call-command-if-ca)
Allows for circumstances where you want to call a block that completes immediately multiple times such as in recursion.
Removes the need to put Wait 1 Frame commands in a number of cases
More verbose logging in cases where a block cannot be called as it is already running, which seemed to cause the initial confusion in the linked thread.

New Call mode, StopThenCall

---

Assets/Fungus/Scripts/Components/PortraitController.cs
Assets/Fungus/Scripts/Components/SayDialog.cs

#741 by using overrideSprite instead of sprite on UIImages

Portrait 2019 fix

---

Assets/Fungus/Scripts/Editor/FlowchartWindow.cs

and mousedown( or held over) status of blocks and fixes
-multi move
-multi delete
-multi copy & paste
-control click and marque toggles block selectedness
-undo redo forces refresh of cached lists

FlowchartWindow MutliSelect now more strictly manages selectedness

---

Assets/Fungus/Scripts/Editor/FungusEditorPreferences.cs
Assets/Fungus/Scripts/Editor/PopupContent/CommandSelectorPopupWindowContent.cs
Assets/Fungus/Scripts/Editor/PopupContent/EventSelectorPopupWindowContent.cs
Assets/Fungus/Scripts/Editor/PopupContent/VariableSelectPopupWindowContent.cs

Can still be disabled via project settings "Legacy Menus"

Experimental Searchable menus are now enabled by default

---

Assets/Fungus/Fungus.asmdef
Assets/Fungus/Fungus.asmdef.meta
Assets/Fungus/Scripts/Editor/FungusEditor.asmdef
Assets/Fungus/Scripts/Editor/FungusEditor.asmdef.meta
Assets/Fungus/Thirdparty/FungusLua/Scripts/Editor/Fungus.FungusLuaEditor.asmdef
Assets/Fungus/Thirdparty/FungusLua/Scripts/Editor/Fungus.FungusLuaEditor.asmdef.meta
Assets/Fungus/Thirdparty/LineEndings/Editor/Fungus.LineEndingsEditor.asmdef
Assets/Fungus/Thirdparty/LineEndings/Editor/Fungus.LineEndingsEditor.asmdef.meta
Assets/Fungus/Thirdparty/Usfxr/Editor/Fungus.UsfxrEditor.asmdef
Assets/Fungus/Thirdparty/Usfxr/Editor/Fungus.UsfxrEditor.asmdef.meta
Assets/FungusExamples/FungusExamples.asmdef
Assets/FungusExamples/FungusExamples.asmdef.meta

Has been mentioned / requested on gitter and in the forum

Add Asmdefs

---

Assets/Fungus/Scripts/Editor/FungusEditorPreferences.cs

Button to locate FungusEditorResources SO to aid in correcting errors due to version changes
Button to open the CHANGELOG to help in identifying users version of Fungus

Fungus editor resources locator

---

Assets/Fungus/Scripts/Components/Writer.cs
Assets/Tests/WritingSpeedTest.unity
Assets/Tests/WritingSpeedTest.unity.meta

As reported on the forum, [link](http://fungusgames.com/forum#!/general:textmeshpro-richtext-and-li)
Writing letter by letter at higher than frame rate would end up limited to 1 char per frame in certain circumstances

High speed writer fix

---

Assets/Fungus/Scripts/Editor/CommandListAdaptor.cs

-Cache GUISkins at CommandListAdapter creation
Fix #772

Show Command Summary text in red if it has Error:

---

Assets/Fungus/Scripts/Commands/Call.cs
Assets/Fungus/Scripts/Commands/Menu.cs
Assets/Fungus/Scripts/Commands/MenuTimer.cs
Assets/Fungus/Scripts/Commands/StopBlock.cs
Assets/Fungus/Scripts/Editor/BlockEditor.cs
Assets/Fungus/Scripts/Interfaces/IBlockCaller.cs
Assets/Fungus/Scripts/Interfaces/IBlockCaller.cs.meta
Assets/Fungus/Scripts/Utils/BlockReference.cs

As requested #653
IBlockCaller added and shown in BlockEditor

Show all IBlockCallers in BlockEditor

---

Assets/Fungus/Scripts/Commands/Call.cs
Assets/Fungus/Scripts/Commands/DebugBreak.cs
Assets/Fungus/Scripts/Commands/DebugBreak.cs.meta
Assets/Fungus/Scripts/Components/Block.cs
Assets/Fungus/Scripts/Components/Command.cs
Assets/Fungus/Scripts/Components/EventHandler.cs
Assets/Fungus/Scripts/Components/MenuDialog.cs
Assets/Fungus/Scripts/Components/Variable.cs
Assets/Fungus/Scripts/Editor/BlockEditor.cs
Assets/Fungus/Scripts/Editor/EditorExtensions.cs
Assets/Fungus/Scripts/Editor/FlowchartWindow.cs
Assets/Fungus/Scripts/Editor/PopupContent/VariableSelectPopupWindowContent.cs
Assets/Fungus/Scripts/Editor/VariableListAdaptor.cs
Assets/Fungus/Scripts/Interfaces/IBlockCaller.cs
Assets/Fungus/Scripts/Interfaces/IStringLocationIdentifier.cs
Assets/Fungus/Scripts/Interfaces/IStringLocationIdentifier.cs.meta
Assets/Fungus/Scripts/Interfaces/IVariableReference.cs
Assets/Fungus/Scripts/Interfaces/IVariableReference.cs.meta
Assets/Fungus/Scripts/Utils/VariableReference.cs

Partial #771 
- Debug.Break equiv in a Fungus Command
- Right Click on Blocks and Variables provides additional actions, like Execute, Stop, Find references, and sorting

Debug additions

---

Assets/Fungus/Scripts/Commands/FadeScreen.cs
Assets/Fungus/Scripts/Commands/FadeToView.cs
Assets/Fungus/Scripts/Commands/MoveToView.cs
Assets/Fungus/Scripts/Components/CameraManager.cs
Assets/FungusExamples/FungusTown/FungusTown.unity

CameraManager and View related Commands now use LeanTweenTypes

---

Assets/Fungus/Scripts/Commands/VariableCondition.cs
Assets/Fungus/Scripts/Editor/VariableConditionEditor.cs
Assets/FungusExamples/Conditions.meta
Assets/FungusExamples/Conditions/MultipleConditionsExample.unity
Assets/FungusExamples/Conditions/MultipleConditionsExample.unity.meta

Fixes issue #778 
created basic support for multiple conditions using logic anyOneTrue or allTrue from a list of conditions. 
- Need suggestions for UI improvements. 
- One problem i have noticed is that indenting breaks the data variable field of AnyVariableAndDataPair in the custom inspector.
- For backward compatibility setting the anyVar field to null doesn't seem to work. it seems to get reinitialized on changing the number of condition. so for now I am checking if anyVar.variable != null to skip backward compatibility.

basic support for multiple conditions added

---

Assets/Fungus/Scripts/Utils/ConversationManager.cs

Fix showing hidden portrait in conversation

---

Assets/Fungus/Scripts/Editor/FlowchartWindow.cs

Changes to 2019.3 unity ui had caused the popup box to fail to draw correctly
Fix #818

Fix FlowchartWindow Search Popup

---

Assets/Fungus/Thirdparty/FungusLua/Scripts/Utils/PODTypeFactory.cs

constuct => construct
Typo change
N/A

Update typo in PODTypeFactory.cs

---

Assets/Fungus/Scripts/Commands/SetSliderValue.cs
Assets/Fungus/Scripts/EventHandlers/SliderChanged.cs
Assets/Fungus/Scripts/EventHandlers/SliderChanged.cs.meta

and Add get logic to SetSliderValue
Related to ongoing request for interaction between ui elements and Fungus. Such as #839
Firing blocks via SliderChanged Event Handler, value passed from the slider can be caught in the variable provided to the event handler and then used in the block. Also added Get logic path to the SetSliderValue command.
- My change require modifications or additions to documentation

Add Slider EventHandler

---

Assets/Fungus/Scripts/Components/CameraManager.cs
Assets/Tests/Overlapping_Flash.unity
Assets/Tests/Overlapping_Flash.unity.meta

Fixes stack overflow recusion bug when fades are called in a cascading/overlapping fashion.
closes #973

Camera Fade needs to be cleared before called

---

Assets/Fungus/Docs/CHANGELOG.txt
Assets/Fungus/Scripts/Components/PortraitController.cs

Close #922
This is presently only tested against reported case found in demo scene 'The Experiment'.

Force new portrait in Show to undimmed
